---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Packages
library(stringr)
library (knitr)
```



```{r load}
#Load the raw data
rawData<-read.csv("Week 3 /Raw Data/Week 3 Example Data.csv")
c
#Create a copy of the raw data
data<-rawData

```




```{r restructure}

colnames(data)[6:15]<-paste0("tipi",
                             rep(c("E","A","C","N","O"),2),
                             1:10)
colnames(data)[c(7,11,13:15)]<-paste0(colnames(data)[c(7,11,13:15)],"R")

#Restructure variables#

#Split the condition variable into two columns
ConditionSplit<-str_split_fixed(data$condition,"_",2)

#Rename the newly created condition variables
colnames(ConditionSplit)<-c("shockCause", "pMoral")

#Add the split columns back to the data
data<-cbind(data,ConditionSplit)

data<-data[,-4]

#Recode missing values as NA 
data$guilt<-ifelse(data$guilt==-99,NA,data$guilt)
```









```{r compute}

#Reverse code the relevant TIPI items 
data[,c(6,10,12:14)]<-(-1*data[,c(6,10,12:14)])+8

#Compute composite personality scores
data$extra<-rowMeans(data[,c(5,10)])
data$agree<-rowMeans(data[,c(6,11)])
data$consc<-rowMeans(data[,c(7,12)])
data$neuro<-rowMeans(data[,c(8,13)])
data$open<-rowMeans(data[,c(9,14)])

```


```{r codebook}
#Rearrange
data<-data[,c(1:3,5:14,20:24,4,18:19,15:17)]

codebook<-data.frame("variable"=colnames(data))

codebook$description<-c(
  "Participant ID number",
  "Participant Sex",
  "Age",
  "TIPI Extraversion 1",
  "TIPI Agreeableness 1 (R)",
  "TIPI Conscientiousness 1",
  "TIPI Neuroticism 1",
  "TIPI Openness 1",
  "TIPI Extraversion 2 (R)",
  "TIPI Agreeableness 2",
  "TIPI Conscioustiousness 2 (R)",
  "TIPI Neuroticism 2 (R)",
  "TIPI Openness 2 (R)",
  "Composite Extraversion",
  "Composite Agreeableness",
  "Composite Conscioustiousness",
  "Composite Neuroticism",
  "Composite Openness",
  "Shock Voltage",
  "Shock Cause (participant vs. partner)",
  "Partner Morality (good vs. bad)",
  "Amount of $ shared with partner (pre shock)",
  "Amount of $ shared with partner (post shock)",
  "Guilt reported by participant"
)

#save the types of variables
codebook$type<-sapply(data,class)

#output the codebook as a table 
kable(codebook)

```

```{r save}
#Save the data 
write.csv(data,"Week 3 /Processed Data/Week 3 Data PROCESSED.csv")


```